# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
# kubectl create -f ./.k8s/deployment.yml
# kubectl delete -f ./.k8s/deployment.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-subgraph-deployment
  labels:
    app: user-subgraph
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-subgraph
  template:
    metadata:
      labels:
        app: user-subgraph
    spec:
      containers:
        - name: user-subgraph
          image: registry.digitalocean.com/from-the-forest/user-subgraph:latest
          ports:
            - containerPort: 4000
