# https://kubernetes.io/docs/concepts/services-networking/service/
# kubectl create -f ./.k8s/service.yml
# kubectl delete -f ./.k8s/service.yml
apiVersion: v1
kind: Service
metadata:
  name: user-subgraph-service
spec:
  selector:
    app: user-subgraph
  ports:
    - port: 4000
  type: ClusterIP
