# https://kubernetes.io/docs/concepts/services-networking/service/
# kubectl create service -f ./.k8s/service.yml
# kubectl delete service -f ./.k8s/service.yml
# apiVersion: v1
# kind: Service
# metadata:
#   name: user-subgraph-service
# spec:
#   selector:
#     app.kubernetes.io/name: proxy
#   ports:
#     - name: name-of-service-port
#       protocol: TCP
#       port: 80
#       targetPort: http-web-svc
