version: 2.1

orbs:
  go: circleci/go@1.7.1
  docker: circleci/docker@2.2.0

jobs:
  install:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache

  secrets:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: |
          echo "PORT=4000" >> .env
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .env
      - store_artifacts:
          path: .env

  test:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  lint:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: make lint

  build:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      # get .env from secrets job.
      - attach_workspace:
          at: /home/circleci/project
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: make build
      - docker/install-docker
      - docker/build:
          image: ftf/user-subgraph
          tag: latest

workflows:
  version: 2
  primary:
    jobs:
      - install
      - secrets
      - lint
      - test:
          requires:
            - install
            - secrets
      - build:
          requires:
            - install
            - secrets

  # nightly:
  #   triggers:
  #     - schedule:
  #         cron: "0 0 * * *" # ~8PM EST.
  #         filters:
  #           branches:
  #             only:
  #               - main
  #   jobs:
  #     - cleanup
