version: 2.1

orbs:
  go: circleci/go@1.7.1
  docker: circleci/docker@2.2.0

jobs:
  install:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache

  secrets:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: |
          echo "PORT=4000" >> .env
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .env
      - store_artifacts:
          path: .env

  test:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  lint:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: make lint

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check
      - docker/build:
          image: ftf/user-subgraph
          tag: latest
      - docker/push:
          digest-path: /tmp/digest.txt
          image: ftf/user-subgraph
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  version: 2
  primary:
    jobs:
      - install
      - secrets
      - test:
          requires:
            - install
            - secrets
      - build-and-push:
          requires:
            - install
            - secrets
            - test
