version: 2.1

orbs:
  go: circleci/go@1.7.1
  docker: circleci/docker@2.2.0
  doctl: digitalocean/cli@0.1.1
  kubernetes: circleci/kubernetes@1.3.1

jobs:
  install:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache

  secrets:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: |
          echo "PORT=4000" >> .env
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - .env
      - store_artifacts:
          path: .env

  test:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true

  lint:
    executor:
      name: go/default
      tag: 1.19.4
    steps:
      - checkout
      - run: make lint

  build-and-push:
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          registry: registry.digitalocean.com/from-the-forest
          docker-username: DO_TOKEN
          docker-password: DO_TOKEN
      - docker/build:
          registry: registry.digitalocean.com/from-the-forest
          image: user-subgraph
          tag: $CIRCLE_SHA1
      - docker/push:
          registry: registry.digitalocean.com/from-the-forest
          image: user-subgraph
          tag: $CIRCLE_SHA1
      # TODO: also push the tag as latest
      # - docker/build:
      #     registry: registry.digitalocean.com/from-the-forest
      #     image: user-subgraph
      #     tag: latest
      # - docker/push:
      #     registry: registry.digitalocean.com/from-the-forest
      #     image: user-subgraph
      #     tag: latest

  deploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - checkout
      - kubernetes/install
      - doctl/install
      - doctl/initialize:
          digitalocean-access-token: DO_TOKEN
      - run: doctl kubernetes cluster kubeconfig save ftf-main-cluster
      - kubernetes/update-container-image:
          container-image-updates: user-subgraph=registry.digitalocean.com/from-the-forest/user-subgraph:$CIRCLE_SHA
          resource-file-path: ./.k8s/deployment.yml
      - kubernetes/create-or-update-resource:
          resource-file-path: ./.k8s/deployment.yml

workflows:
  version: 2
  primary:
    jobs:
      - install
      - secrets
      - test:
          requires:
            - install
            - secrets
      - build-and-push:
          context: ftf
          requires:
            - install
            - secrets
            - test
      - deploy:
          context: ftf
          requires:
            - build-and-push
