// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"user/graph/scalar"
)

type Node interface {
	IsNode()
	// Relay node id
	GetID() string
}

// User type
type User struct {
	// User's first name
	FirstName string `json:"firstName"`
	// Node ID
	ID string `json:"id"`
	// User's last name
	LastName string `json:"lastName"`
	// User's full name (example of a compound field)
	FullName string `json:"fullName"`
	// User's email address
	Email scalar.Email `json:"email"`
}

func (User) IsNode() {}

// Relay node id
func (this User) GetID() string { return this.ID }

func (User) IsEntity() {}
