// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type User struct {
	// Node ID
	ID string `json:"id"`
	// User's first name
	FirstName string `json:"firstName"`
	// User's last name
	LastName string `json:"lastName"`
}
